---
- hosts: web
  tasks:
    - name: Create user
      user:
        name: app
        generate_ssh_key: True
        state: present
    - name: Set authorized key taken from file
      authorized_key:
        user: app
        state: present
        key: "{{ lookup('file', 'app.pub') }}"
        manage_dir : False

